sudo: false

language: python

matrix:
  include:
    - os: linux
      python: '2.7'
      env: CONDA=true
    - os: linux
      python: '3.6'
      env: CONDA=true
    - os: linux
      python: '3.7'
      env: CONDA=true
    - os: osx
      language: generic
      env: CONDA=true TRAVIS_PYTHON_VERSION=2.7
    - os: osx
      language: generic
      env: CONDA=true TRAVIS_PYTHON_VERSION=3.6
    - os: osx
      language: generic
      env: CONDA=true TRAVIS_PYTHON_VERSION=3.7

branches:
  except:
    - ConjugateEverything
    - ConjugateEverythingPages

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then lsb_release -a ; fi

install:
  - PYTHON_VERSION="${TRAVIS_PYTHON_VERSION}" CONDA_INSTALLER_OS="${TRAVIS_OS_NAME:-linux}" source auto_version/travis_install_conda.sh numpy scipy numba pip pytest mpmath sympy
  - conda config --set anaconda_upload yes
  - conda install -n root conda-build anaconda-client
  - pip install packaging
  - conda install -c moble quaternion spinsfast
  - git checkout "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}"
  - git reset --hard "${TRAVIS_COMMIT}"
  - python setup.py install

script:
  # I've had to make some tests' accuracy depend on the value of
  # ell_max, so I run the tests for multiple values of ell_max.  And
  # then I run again for the largest ell_max, but only the faster
  # tests, so that Travis isn't overtaxed.  (Those slower tests have
  # already established their patterns anyway; the interesting tests
  # for large ell_max are the ones likely overflow and underflow,
  # which are pretty fast.)
  # - py.test test_* --cov=spherical_functions --ell_max 8 --run_slow_tests -s
  - py.test --ell_max 4 --run_slow_tests -s
  - py.test --ell_max 32 -s

after_success:
  - python ./.meta_yaml_replacer.py
  - conda build --token "$ANACONDA_TOKEN" .

deploy:
  - provider: pypi
    user: moboyle79
    skip_upload_docs: true
    password:
      secure: Dksv2EeU1Kgavi9aTKabbojuAaY3ZWscX4PLSF2HfISpdwfq6uTbyJr/UO584/1NMmPUslIFHY+PU47+klizYSMqsRYSLnBXnRITxWym9RDsW3bhZq4rUCik6P35fQsCeNdJ6idWwAyR2B3PGbEbmuIxJ5zvnFYJnlwinFqgmKc=
    on:
      distributions: sdist bdist_wheel
      repo: moble/spherical_functions
      python: '3.7'
      condition: $CONDA = 'true'

after_script:
  # if we do not unset this before we terminate the travis teardown will mark the entire job as failed
  - set +e
